package:
    name: thermo
    version: master

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - vcs
    - cdms2

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



