package:















    name: mesalib















    version: 7.6.1































source:















    fn:  MesaLib-7.6.1.tar.gz















    url: http://uvcdat.llnl.gov/cdat/resources/MesaLib-7.6.1.tar.gz















    md5: e80fabad2e3eb7990adae773d6aeacba















































build:















    string: UVCDAT















