package:
    name: regrid2
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - libcdms
    - cdat_info
    - numpy <=1.9.2
  run:
    - python
    - libcdms
    - cdat_info
    - numpy <=1.9.2
    - esmf

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



