package:
    name: vistrails
    version: master

source:
    git_rev: uvcdat-master
    git_url: git://github.com/UV-CDAT/VisTrails.git

build:
  string: UVCDAT
 
requirements:
  build:
  run:
    - numpy <=1.9.2
    - scipy
    - pyqt
    - uvcmetrics
    - matplotlib

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



