package:
    name: libcdms
    version: master

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/libcdms.git

build:
  string: UVCDAT
 
requirements:
  build:
    - hdf5
    - libnetcdf 4.3.3.1
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg
  run:
    - hdf5
    - libnetcdf 4.3.3.1
    - jasper
    - g2clib
    - libpng
    - libtiff
    - jpeg

about:
    home:  http://gitub.com/UV-CDAT/libcdms



