package:
    name: yasm
    version: 1.2.0

source:
    fn:  yasm-1.2.0.tar.gz
    url: http://uvcdat.llnl.gov/cdat/resources/yasm-1.2.0.tar.gz
    md5: 4cfc0686cf5350dd1305c4d905eb55a6


requirements:
    build:
        - python
    run:
        - python
build:
    string: UVCDAT

about:



