package:
    name: lapack
    version: 3.4.2

source:
  fn: lapack-3.4.2-CMAKE.tgz
  url: http://uvcdat.llnl.gov/cdat/resources/lapack-3.4.2.tgz

build:
  number: 2

requirements:
  build:
    - cmake
    - gfortran [osx]
  run:
    - gfortran [osx]

about:
    home:  http://gitub.com/UV-CDAT/uvcdat




