package:
  name: libjson-c
  version: "0.12"
 
source:
  git_branch: master
  git_url: https://github.com/json-c/json-c.git
 
build:
  string: PCMDI

requirements:
  build:
  run:
 
test:
  imports:
 
about:
  home: https://github.com/json-c/json-c/wiki
