package:
    name: genutil
    version: 2.4.0

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - numpy
  run:
    - python
    - cdms2
    - cdutil

about:
    home:  http://gitub.com/UV-CDAT/uvcdat
