package:
    name: genutil
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - numpy <=1.9.2
  run:
    - python
    - cdms2
    - cdutil
    - unidata
    - numpy <=1.9.2

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



