package:
    name: cmor
    version: 2.9.2

source:
    git_rev: master
    git_url: http://github.com/PCMDI/cmor.git

build:
  string: PCMDI
 
requirements:
  build:
    - python
    - ossuuid 1.6.2
    - udunits
    - hdf5 
    - libnetcdf 4.3.3.1
    - numpy <=1.9.2
  run:
    - python
    - ossuuid 1.6.2
    - udunits
    - hdf5
    - libnetcdf 4.3.3.1
    - numpy <=1.9.2
    - cdms2

about:
    home:  http://gitub.com/PCMDI
