package:
  name: cmor
  version: "3.0alpha"
 
source:
  git_rev: cmor3
  git_url: https://github.com/PCMDI/cmor.git

build:
  string: PCMDI
 
requirements:
  build:
    - python    [unix]
    - libhdf5   [unix]
    - libnetcdf [unix]
    - libjson-c [unix]
    - ossuuid   [unix]
    - udunits   [unix]
    - numpy
  run:
    - python    [unix]
    - libhdf5   [unix]
    - libnetcdf [unix]
    - libjson-c [unix]
    - ossuuid   [unix]
    - udunits   [unix]
    - numpy
 
test:
  imports:
 
about:
  home: https://github.com/PCMDI/cmor
