package:
    name: cmor
    version: 3.0alpha

source:
    git_rev: cmor3
    git_url: http://github.com/PCMDI/cmor.git

build:
  string: PCMDI
 
requirements:
  build:
    - python
    - ossuuid 1.6.2 PCMDI
    - udunits 2.2.20 PCMDI
    - libhdf5 1.8.16 PCMDI
    - netcdf 4.4.0 PCMDI
    - libjson-c 0.12 PCMDI
    - numpy
  run:
    - python
    - ossuuid
    - udunits
    - libhdf5
    - netcdf
    - libjson-c
    - numpy

about:
    home:  http://gitub.com/PCMDI
