package:
    name: uvcdat
    version: master

source:

build:
  string: UVCDAT
 
requirements:
  build:
  - jasper
  - g2clib
  - hdf5
  - libnetcdf 4.3.3.1
  - lapack >=3.4.2
  - clapack >=3.2.1
  - curl
  - python
  - ossuuid 
  - libcdms
  - regrid2
  - libcf
  - distarray
  - cdms2
  - cdtime
  - cdutil
  - cmor
  - dv3d
  - esg
  - genutil
  - pydebug
  - regrid2
  - thermo
  - unidata
  - uvcmetrics
  - vcs
  - vcsaddons
  - vistrails
  - wk
  - xmgrace

  run:
  - g2clib
  - jasper
  - libcdms
  - python
  - regrid2
  - libcf
  - distarray
  - cdms2
  - cdtime
  - cdutil
  - cmor
  - dv3d
  - esg
  - genutil
  - pydebug
  - regrid2
  - thermo
  - unidata
  - uvcmetrics
  - vcs
  - vcsaddons
  - vistrails
  - wk
  - xmgrace


about:
  home:  http://gitub.com/UV-CDAT/uvcdat



