package:
    name: uvcdat
    version: master

source:

build:
  string: UVCDAT
 
requirements:
  build:
  - python
  - regrid2
  - libcf
  - distarray
  - cdms2
  - cdtime
  - cdutil
  - cmor
  - dv3d
  - esg
  - genutil
  - pydebug
  - regrid2
  - thermo
  - unidata
  - uvcmetrics
  - vcs
  - vcsaddons
  - vistrails
  - wk
  - xmgrace

  run:
  - python
  - regrid2
  - libcf
  - distarray
  - cdms2
  - cdtime
  - cdutil
  - cmor
  - dv3d
  - esg
  - genutil
  - pydebug
  - regrid2
  - thermo
  - unidata
  - uvcmetrics
  - vcs
  - vcsaddons
  - vistrails
  - wk
  - xmgrace


about:
  home:  http://gitub.com/UV-CDAT/uvcdat



