package:
    name: dv3d
    version: 2.4.0

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - vtk
  run:
    - python
    - vtk
    - vcs
    - cdms2

about:
    home:  http://gitub.com/UV-CDAT/uvcdat
