package:
  name: ossuuid
  version: "1.6.2"
 
source:
  fn: uuid-1.6.2.tar.gz
  url: http://www.mirrorservice.org/sites/ftp.ossp.org/pkg/lib/uuid/uuid-1.6.2.tar.gz
 
build:
  string: PCMDI

requirements:
  build:
  run:
 
 
about:
  home: ftp://ftp.ossp.org/pkg/lib/uuid/
