package:
  name: ossuuid
  version: "1.6.2"
 
source:
  fn: uuid-1.6.2.tar.gz
  url: http://www.mirrorservice.org/sites/ftp.ossp.org/pkg/lib/uuid/uuid-1.6.2.tar.gz
#  url: ftp://ftp.ossp.org/pkg/lib/uuid/uuid-1.6.1.tar.gz
 
requirements:
  build:
  run:
 
test:
  imports:
 
about:
  home: ftp://ftp.ossp.org/pkg/lib/uuid/
  license: BSD
