package:
    name: cdms2
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - regrid2
  run:
    - python
    - regrid2
    - libcf
    - distarray
    - esmf

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



