package:
    name: cdutil
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
  run:
    - python
    - cdms2

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



