package:
    name: uvcmetrics
    version: 2.4.0

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcmetrics.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - numpy <=1.9.2
  run:
    - python
    - numpy <=1.9.2
    - vcs
    - cdms2

about:
    home:  http://gitub.com/UV-CDAT/libcdms
