package:
    name: gui_support
    version: 2.4.0

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python

about:
    home:  http://gitub.com/UV-CDAT/uvcdat
