package:
  name: udunits
  version: 2.2.20
 
source:
  fn: udunits-2.2.20.tar.gz
  url: ftp://ftp.unidata.ucar.edu/pub/udunits/udunits-2.2.20.tar.gz
 
build:
  string: PCMDI

requirements:
  build:
  run:
 
 
about:
  home: ftp://ftp.unidata.ucar.edu/pub/udunits/
