package:















  name: udunits2















  version: 2.2.17















 















source:















  fn: udunits-2.2.17.tar.gz















  url: http://uvcdat.llnl.gov/cdat/resources/udunits-2.2.17.tar.gz















 















build:















    string: UVCDAT































requirements:















  build:















  run:















 















 















about:















  home: ftp://ftp.unidata.ucar.edu/pub/udunits/































































