package:















  name: libhdf5















  version: "1.8.16"















 















source:















  fn: hdf5-1.8.16.tar















  url: http://www.hdfgroup.org/ftp/HDF5/current/src/hdf5-1.8.16.tar.bz2































build:















  string: UVCDAT















 















requirements:















  build:















  run:















 















test:















  imports:















 















about:















  home: https://www.hdfgroup.org































































