package:
    name: wk
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
  run:
    - python
    - cdms2
    - vcs

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



