package:
    name: esmf
    version: ESMF_6_3_0rp1_ESMP_01

source:
    fn:  esmp.ESMF_6_3_0rp1_ESMP_01.tar.gz
    url: http://uvcdat.llnl.gov/cdat/resources/esmp.ESMF_6_3_0rp1_ESMP_01.tar.bz2

build:
  string: UVCDAT
 
requirements:
  build:
    - python
  run:
    - python

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



