package:
    name: cdtime
    version: master

source:
    git_rev: master
    git_url: http://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - libcdms
    - cdat_info
  run:
    - python
    - setuptools
    - libcdms
    - cdat_info

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



