package:
    name: vcs
    version: master

source:
    git_rev: master
    git_url: git://github.com/UV-CDAT/uvcdat.git

build:
  string: UVCDAT
 
requirements:
  build:
    - python
    - setuptools
    - cdat_info
  run:
    - python
    - cdat_info
    - genutil
    - unidata
    - dv3d
    - vtk
    - cdms2
    - cdutil

about:
    home:  http://gitub.com/UV-CDAT/uvcdat



