package:
    name: netcdf
    version: 4.4.0

source:
    fn:  netcdf-4.4.0.tar.gz
    url: ftp://ftp.unidata.ucar.edu/pub/netcdf/netcdf-4.4.0.tar.gz

requirements:
    build:
        - libhdf5 # [unix]
    run:
        - libhdf5
build:
    string: PCMDI

about:
    home:  http://hdfgroup.org 



