package:
  name: netcdf
  version: "4.4.0"
 
source:
  fn: netcdf-4.4.0.tar.gz
  url: file://home/dnadeau/netcdf-4.4.0.tar.gz
#  url: ftp://ftp.ossp.org/pkg/lib/uuid/uuid-1.6.1.tar.gz
 
requirements:
  build:
  run:
 
test:
  imports:
 
about:
  home: https://www.hdfgroup.org
