package:
    name: cdat_info
    version: 2.4.0

source:

build:
  string: UVCDAT
 
requirements:
  build:
   - python
   - setuptools
  run:
   - python

about:
    home:  http://gitub.com/UV-CDAT/uvcdat
