package:
    name: ffmpeg
    version: 2.7.0

source:
    fn:  ffmpeg-2.7.0.tar.gz
    url: http://uvcdat.llnl.gov/cdat/resources/ffmpeg-2.7.tar.gz
    md5: 3ad0554981faf2c6deef23a1cd4c8c57


requirements:
    build:
        - x264
    run:
        - x264
build:
    string: UVCDAT
